### ISSUE TITLE
Error on user registration

### ISSUE THREAD

**Issue by reliaboe** [mimir-org/typelibrary#177]
If you have created a none valid schema in user registration, nothing happend on the second try. You have to refresh the page. This happens in dev environment.

I tried to regigister a user with not valid password. First there is a message with none valid password length. I replace the password, and nothing happens. None call to backend application.

**Comment by Fruithut** [comment]
Having some trouble reproducing this issue @reliaboe.
If I replace both password fields with a valid password after getting an error for them I am still able to submit 🤔

**Comment by Fruithut** [comment]
Closing this issue since the registration flow is being reimplemented with #81 💡
