### ISSUE TITLE
Server: Get data from PCA - Symbol

### ISSUE THREAD

**Issue by reliaboe** [mimir-org/typelibrary#199]
We need to import symbols from PCA instead of saving symbols in Tyle DB.
https://rds.posccaesar.org/ontology/plm/rdl/PCA_100004125/

- Create new external repository, and point it to PCA ontology
- Refactor symbols for Tyle and Mimir

This is on hold because of missing data from PCA

**Comment by reliaboe** [comment]
There is a bug asking for symbols in PCA. Mail is sent and will update this task when problem is solved.

**Comment by kahovden** [comment]
Spørring for å hente ut:

PREFIX foaf: <[http://xmlns.com/foaf/0.1/>](http://xmlns.com/foaf/0.1/%3E)
PREFIX rdfs: <[http://www.w3.org/2000/01/rdf-schema#>](http://www.w3.org/2000/01/rdf-schema#%3E)
PREFIX owl: <[http://www.w3.org/2002/07/owl#>](http://www.w3.org/2002/07/owl#%3E)
PREFIX lis: <[http://rds.posccaesar.org/ontology/lis14/rdl/>](http://rds.posccaesar.org/ontology/lis14/rdl/%3E)PREFIX rdl:   <[http://rds.posccaesar.org/ontology/plm/rdl/>](http://rds.posccaesar.org/ontology/plm/rdl/%3E)
select ?datum ?datum_label ?imgfile {    ?datum a rdl:PCA_100004920   ; rdfs:label ?datum_label .    optional { ?datum rdfs:comment ?dcomm . }    optional { ?datum foaf:Image ?imgfile . }
} order by ?datum_label
