### ISSUE TITLE
Client: Exploratory testing. Bugs found and feedback.

### ISSUE THREAD

**Issue by kahovden** [mimir-org/typelibrary#219]
Hei @Fruithut. Satt å testet backend i dag via klienten og oppdaget litt ting og tang i klienten som jeg tenkte jeg skulle notere ned. Noe av det er bugs, mens andre ting er mer min brukeropplevelse. Snakk gjerne med meg om noe er uklart eller snakk med @Arjunch00 hvis du har lyst til å gjøre noen GUI endringer/forbedringer.  

> Attribute endringer utgår ref #223 
> 
> **Create Attribute**
> 
> - Hvis jeg velger en 'References' dukker 'Units' opp og under 'Units' dukker det opp en horisontal liste som nå er valgt. Det kommer ikke tydelig nok frem i visningen at disse faktisk nå er valgt. Kanskje en X (eller bosspann) i øvre høyre hjørne kan gi brukeren beskjed om at disse unit'ene er valgt? Og ved trykk på X blir de fjernet?  
> - Hvis jeg trykker på + ikonet ved 'Units' kommer det opp et vindu hvor jeg kan 'Add' flere units. Men de som allerede er lagt til kommer også opp. Her bør vi fjerne de som allerede er valgt fra listen og kun tilgjengelige units (som ikke allerede er lagt til) bør vises?
> - Hvis en velger 'Selection' 'SingleSelect' dukker 'Values' opp. Hvis en så trykker på + ikonet kommer et felt opp der en kan sette inn en verdi. Hvis en nå trykker bosspannet kommer en rød feilmelding 'Please create one or more values to select from'. Hvis jeg nå trykker + igjen og legger inn en verdi står fortsatt teksten 'Please create one or more values to select from'. Denne feilmeldingsteksten bær vel nå fjernet?
> - Hvis en velger 'Selection' 'MultiSelect' dukker 'Values' opp. Hvis jeg nå legger til kun 1 value kan jeg trykke submit og det lagres til server. Bør ikke en 'MultiSelect' ha krav om minimum 2 verdier?
> 
> **Edit/Clone Attribute**
> 
> - Hvis jeg fra hovedvisningen trykker på en attribut en gang med venstre mus vises attributt egenskapene i en vindu/felt til høyre på skjermen. Her er 'Units' på attributten korrekt. Men hvis jeg trykker edit eller clone på denne attributen stemmer ikke 'Units' med attributten. 'Units' listen som er valgt blir satt til default og ikke som som faktisk er på attributten fra før. Hvis jeg har trykket edit og nå endrer 'description' og trykker 'Submit' blir attributten lagret med mange (alle) nye 'Units' og blir dermed version 2.0. Skulle vært versjon 1.1 men siden det kommer inn mange nye attributter som øker versjonen til neste major. Feilen er altså at klienten ikke har korrekte 'Units' når en klikker edit eller clone.
> - Attribute (låses): Name, Aspect, QuantityDatumSpecifiedScope, QuantityDatumSpecifiedProvenance, QuantityDatumRangeSpecifying, QuantityDatumRegularitySpecified. 
> - Attribute (kun legge til): References, Units og Values.  
> 
> **Create Aspect object**
> 
> - Hvis jeg trykker + ikonet ved siden av 'Terminals' kan jeg velge en terminal som jeg har laget tidligere. Men denne terminalen sine 'Terminal attributes' vises ikke i visningen. Hvis jeg legger til en til terminal (2 stk. nå) så dukker 'Terminal attributes' opp på linjen over men mangler på linjen jeg nettopp la til. Hvis jeg legger til en tredje terminal så dukker 'Terminal attributes' opp på linjen over men mangler på linjen jeg nettopp la til. Altså så mangler visning av 'Terminal attributes' på den linjen jeg akkurat har lagt til.   
> - Hvis jeg legger til en 'Attributes' og deretter trykker igjen på + ikonet er fortsatt den jeg allerede har valgt tilgjengelig på listen over attributter jeg kan velge. Er bør vel ikke kunne 'Add' (velge) noe som allerede er valgt/add'et? 

**Create Interface**

- Hvis jeg legger til en 'Attributes' og deretter trykker igjen på + ikonet er fortsatt den jeg allerede har valgt tilgjengelig på listen over attributter jeg kan velge. Er bør vel ikke kunne 'Add' (velge) noe som allerede er valgt/add'et? 

**Create Terminal**

- Hvis jeg legger til en 'Attributes' og deretter trykker igjen på + ikonet er fortsatt den jeg allerede har valgt tilgjengelig på listen over attributter jeg kan velge. Er bør vel ikke kunne 'Add' (velge) noe som allerede er valgt/add'et? 

**Create Transport**

- Hvis jeg legger til en 'Attributes' og deretter trykker igjen på + ikonet er fortsatt den jeg allerede har valgt tilgjengelig på listen over attributter jeg kan velge. Er bør vel ikke kunne 'Add' (velge) noe som allerede er valgt/add'et? 

**Klient begrensninger/validering av hvilke felter som IKKE er lov å endre eller fjerne i 'Edit' mode**

- Interface  (låses): Name, RdsCode og Aspect.
- Interface  (kun legge til): Attributes.
- Node (låses): Name, RdsCode og Aspect.
- Node (kun legge til): Terminals og Attributes
- Terminal (låses): Name
- Terminal (kun legge til): Attributes
- Transport (låses): Name, RdsCode og Aspect.
- Transport (kun legge til): Attributes

**Generelle observasjoner**

- 'State' på objektene bør vises et sted.

Slik ser den nye 'Log' tabellen ut etter herjingen min:

![Image](https://user-images.githubusercontent.com/5370607/195570304-34ad81a0-c752-4082-878e-2d619da6b7cd.png)

**Comment by Fruithut** [comment]
Filtering av already selected attributes implemented through: https://github.com/mimir-org/typelibrary/commit/4396175c4a86335d2b3992b4ca4021887baf7845

**Comment by Fruithut** [comment]
Restrictions addressed by https://github.com/mimir-org/typelibrary/pull/275

**Comment by Fruithut** [comment]
State information is now presented as token, see commit: https://github.com/mimir-org/typelibrary/commit/f37b68f2bff482adfbbce8206310ced1bb49c110
