### ISSUE TITLE
Client/Server: Manage user roles

### ISSUE THREAD

**Issue by kahovden** [mimir-org/typelibrary#253]
**Is your feature request related to a problem? Please describe.**
As of today there does not exist a way to assign global user roles. 

**Describe the solution you'd like**
As a global admin, I need to be able to global roles to other users.

**Describe alternatives you've considered**
- Have a link to a new page from the user-menu. This link should only be available if the current user has a global admin role.
- The view where one can assign roles could have
  - A dropdown containing all users.
  - A dropdown with all available roles.

**Additional context**
Might have share some overlapping technical features with #249 

![image](https://user-images.githubusercontent.com/202962/184599483-bfe38bd0-6903-47db-90be-bf8be7f52a94.png)

**Comment by reliaboe** [comment]
I will close this issue
