### ISSUE TITLE
Client/Server: Replace user-email with user-id on types.

### ISSUE THREAD

**Issue by kahovden** [mimir-org/typelibrary#254]
**Is your feature request related to a problem? Please describe.**
As of today the user's email is saved on the entities themselves via the "createdBy" field.
This locks info about the user to data that might need to be persisted longer than the account of the creator.

**Describe the solution you'd like**
We should let createdBy take the userId instead of the more personal email.
We should remove presentation of the createdBy field from the client.

**Describe alternatives you've considered**
None.

**Additional context**

Most of the entities have this field:
![Image](https://user-images.githubusercontent.com/21368234/199044449-afa8060d-78ec-42cb-a452-73a51292741e.png)

**Comment by Fruithut** [comment]
Presentation of createdBy has been removed the client @kahovden 
[feat(client): removes createdBy from entity tokens](https://github.com/mimir-org/typelibrary/commit/d02c88d836a5425baf07b19cf5a4737f111c2fd2)

**Comment by kahovden** [comment]
Implemented on backend @Fruithut and pushed to dev branch. Database column 'CreatedBy' in all tables will now store the user's id (Guid) from the [MimirorgAuthentication].[dbo].[AspNetUsers] table. One new migration was needed for the change from MaxLength 63 to 127 for the 'CreatedBy' column.
