### ISSUE TITLE
Create terminals

### ISSUE THREAD

**Issue by reliaboe** [mimir-org/typelibrary#56]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
As an user, I need to create and update terminals. 

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/202962/184604846-33f32eb7-8458-4a9e-bff0-73917d46cffe.png)

**Comment by Fruithut** [comment]
Feature complete in "feature/forms_terminal". Postponing PR/merge until demo of application is complete.
