### ISSUE TITLE
Create interfaces

### ISSUE THREAD

**Issue by reliaboe** [mimir-org/typelibrary#58]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
As an user, I need to create and update interfaces

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/202962/184606592-b940fafd-7e86-4437-ab0b-962d3780619e.png)

**Comment by Fruithut** [comment]
Feature complete in "feature/forms_interface". Postponing PR/merge until demo of application is complete.
