### ISSUE TITLE
Units sholuld not stay in local database

### ISSUE THREAD

**Issue by reliaboe** [mimir-org/typelibrary#60]
**Is your feature request related to a problem? Please describe.**
The problem with the today solution is that we store units in local db. In the future, we need to integrate with external systems. 

**Describe the solution you'd like**
Remove ef database, and create a temp 'hard-coded' repository with all units. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by kahovden** [comment]
Working in branch: feature/unitRefactor

**Comment by kahovden** [comment]
On hold. We need to discuss this. Much work is done already in branch: feature/UnitRefactor. This task in on hold for now.
